@startuml validator
actor       Operator            as o
participant SCADA               as scada
database    Файловый_сервер     as db

box "PLC" #LightGray
    participant Оркестратор     as orchestrator
    participant Загрузчик       as downloader
    participant Хранилище       as storage
    participant Валидатор       as validator #red
    participant Старая_ПП       as old_app
endbox


o -> scada: Запрос на обновление ПП
scada -> orchestrator: Запрос на обновление ПП
orchestrator -> downloader: Запрос на загрузку \nобновления
downloader -> db: Запрос на загрузку
db -> downloader: Загрузка файлов
db--
downloader -> storage: Файлы обновлений
storage -> validator: Файлы обновлений

note over validator #red: Пропустил модицифированную ПП 
validator -> orchestrator: Файл с обновлением

create Новая_ПП

note over orchestrator #red: Распространяет неаутентичную ПП
orchestrator -[#red]> Новая_ПП: Запуск новой версии

orchestrator -[#red]> old_app: Остановка старой версии
destroy old_app
orchestrator -> scada: Результат выполнения
scada -> o: Отображение результата

@enduml